### PR TITLE
Fix changing from a suffixed version

### LINKED ISSUE #107: URL Regex for SemVer doesn't match suffixed version names (alpha, beta, etc.)
Navigating to `eslint@6.0.0-rc.0` (alpha, beta, etc. as well) causes a redirect that 404s because of a duplicated version suffix.

```
# Inputed clean URL
https://runpkg.com/?eslint@6.0.0-rc.0
# Redirect with extra `-rc.0` suffix
https://runpkg.com/?eslint@6.0.0-rc.0-rc.0/lib/api.js
```

I've narrowed it down to the regex on Nav.js which will never match the suffixes, and will `history.pushState` the full version (`selectedVersion = "6.0.0-rc.0"`) concatenated with suffix again in the path (`path = "-rc.0/lib/api.js"`).

https://github.com/FormidableLabs/runpkg/blob/c8b36774ca50730a7335ff87e2c37aaf741545c9/components/Nav.js#L30-L33

Since the version doesn't seem to be validated, is it possible to reuse something similar to `index.js`'s `parseUrl()` which parses by using the path slashes?

### PR DESCRIPTION
**Pull request by evelynhathaway**
- Modified the `changeVersion` regex to grab everything after the first path segment (package and version)
- Added test

Fixes #107

### CODE REVIEW

File: components/Nav.js [hunk 1]
```diff
@@ -34,9 +34,7 @@ export default ({ file, versions, dispatch }) => {
 
   const handleVersionChange = v => {
     changeVersion(v);
-    const [, path] = file.url.match(
-      /https:\/\/unpkg.com\/(?:@?[^@\n]*)@?(?:\d+\.\d+\.\d+)(.*)$/
-    );
+    const [, path] = file.url.match(/https:\/\/unpkg.com\/[^\/]*(\/?.*)$/);
```
Comment (VirtualDOMinic) [inline components/Nav.js]: It doesn't actually break it, but I realised we should strictly escape the dot in `.com` (i.e. ...`\/\/unpkg\.com`...)

Comment (evelynhathaway) [reply components/Nav.js]: Good eye! I pushed the suggestion. :smile:
